-- DropForeignKey
ALTER TABLE "Bet" DROP CONSTRAINT "FK_Bet_Match";

-- DropForeignKey
ALTER TABLE "Bet" DROP CONSTRAINT "FK_Bet_User";

-- AddForeignKey
ALTER TABLE "Bet" ADD CONSTRAINT "FK_Bet_User" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Bet" ADD CONSTRAINT "FK_Bet_Match" FOREIGN KEY ("matchId") REFERENCES "Match"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
